# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ཏོ་ཧ་T0ha aka Anton Shvein
avatar: /assets/images/t0ha.jpeg
tagline: Full-stack developer, Enterpreneur and Master of Biology
email: t0hashvein@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a full-stack software developer for a dozen of years. Enterpreneur and founder. Master of Biology. PhD studies in progress. Fond of travelling, boldering and sports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://t0ha.ru" # the base hostname & protocol for your site, e.g. http://example.com

lsi: true

twitter_username: t0ha666
github_username:  T0ha
twitter:
  username: t0ha666

author:
  name: Anton Shvein
  email: t0hashvein@gmail.com

header_pages:
  - about-me.md
  - projects.md
  - index.md
  - contacts.md

collections:
  projects:
    sort_by: date
  buddhism:
    sort_by: date
#toc: true
# Build settings
remote_theme: "vszhub/not-pure-poole"
#remote_theme: "jekyll/minima@1e8a445"
show_excerpts: true

#theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-import
  - jekyll-sitemap
    #- jekyll-analytics
  - jekyll-seo-tag
  - jekyll-remote-theme
  - classifier-reborn
  - jekyll_picture_tag
  - jekyll-youtube

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - links.numbers
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: G-SBN1J9XMMJ
