# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ཏོ་ཧ་T0ha aka Anton Shvein
logo: /assets/images/t0ha.jpeg
tagline: Full-stack developer, Enterpreneur and Master of Biology
email: t0hashvein@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a full-stack software developer for a dozen of years. Enterpreneur and founder. Master of Biology. PhD studies in progress. Fond of travelling, boldering and sports.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://t0ha.ru" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: t0ha666
github_username:  T0ha
twitter:
  username: t0ha666

author:
  name: Anton Shvein
  email: t0hashvein@gmail.com

minima:
  social_links:
    - platform: twitter
      user_url: https://twitter.com/T0ha666
    - platform: github
      user_url:  https://github.com/T0ha
    - platform: linkedin
      user_url: https://www.linkedin.com/in/anton-shvein/
    - platform: stackoverflow
      user_url: https://stackoverflow.com/users/3489550/t0ha
    - platform: telegram
      user_url: https://t.me/war1and

header_pages:
  - projects.md
  - index.md
  - contacts.md

collections:
  projects:
    sort_by: date

# Build settings
remote_theme: jekyll/minima
show_excerpts: true
#theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-import
  - jekyll-sitemap
    #- jekyll-analytics
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - links.numbers
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
google_analytics: G-SBN1J9XMMJ
