name: Notify automation for SM
on: 
  workflow_run:
    workflows: [Deploy Jekyll site to Pages]
    types:
      - completed

defaults:
  run:
    shell: bash
env:
  JEKYLL_ENV: production

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Notify Taskade
        run: "curl -X POST -d '{}' -H 'Content-Type: application/json' ${{ secrets.TASKADE_WEBHOOK_URL}}"
